name: Local CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  Docker_image_build:
    runs-on: self-hosted

    steps:
      # 1. Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Docker Login
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t precious0410/devops-app:${{ github.run_number }} .

      # 4. Push Docker Image
      - name: Push Docker Image
        run: |
          docker push precious0410/devops-app:${{ github.run_number }}
  Test:
    runs-on: self-hosted
    needs: Docker_image_build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Test
        run: echo "Testing is successfull"
  Deployment:
    runs-on: self-hosted
    needs: Test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Apply Kubernetes Manifest
        run: |
          kubectl apply -f K8S/deployment.yaml

      # 6. Update Kubernetes Image
      - name: Update Kubernetes Image
        run: |
          kubectl set image deployment/devops-app devops-app=precious0410/devops-app:${{ github.run_number }}

      # 7. Wait for Rollout
      - name: Wait for Deployment
        run: |
          kubectl rollout status deployment/devops-app --timeout=120s
  Deployment_verification:
    runs-on: self-hosted
    needs: Deployment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      # 8. Verify Deployment
      - name: Verify Deployment
        run: |
          echo "===== Deployment ====="
          kubectl get deployment devops-app

          echo "===== Pods ====="
          kubectl get pods -o wide
